webserver:
  host: 0.0.0.0
  port: 8000
  # The URL from which the application will be accessible
  service: https://student-portal.sanger.ac.uk

database:
  # PostgreSQL credentials for CoGS DB
  host: postgres
  port: 5432
  name: postgres
  user: postgres
  passwd: cogs_password

pagesmith_auth:
  # Passphrase for decrypting PageSmith data
  passphrase: pagesmith_passphrase
  database:
    # MySQL credentials for PageSmith DB
    host: web-wwwdb-core-02.internal.sanger.ac.uk
    port: 3449
    user: webcache_ro
    passwd: pagesmith_password
    db: webcache_live

email:
  sender: gradoffice@sanger.ac.uk
  bcc: gradoffice@sanger.ac.uk
  smtp:
    # SMTP server details
    host: mail.sanger.ac.uk
    port: 25
    timeout: 500

general:
  upload_directory: /uploads
  max_filesize: 31457280
  logging_level: DEBUG
