db:
  name: test
  user: sb48
  host: 127.0.0.1

webserver:
  host: 127.0.0.1
  port: 8082
  cookie_key: cYduZe3B?R+kCv\L)f?w(v!VW\pp{#n%

email:
  host: 172.18.255.6
  port: 25
  from: gradoffice@sanger.ac.uk

permissions:
  grad_office:
    modify_permissions: True
    create_project_groups: True
    modify_project_groups: True
    set_readonly: True
    create_projects: False
    review_other_projects: False
    join_projects: False
    view_projects_predeadline: True
    view_all_submitted_projects: True

  supervisor:
    modify_permissions: False
    create_project_groups: False
    modify_project_groups: False
    set_readonly: False
    create_projects: True
    review_other_projects: False
    join_projects: False
    view_projects_predeadline: True
    view_all_submitted_projects: False

  cogs_user:
    modify_permissions: False
    create_project_groups: False
    modify_project_groups: False
    set_readonly: False
    create_projects: False
    review_other_projects: True
    join_projects: False
    view_projects_predeadline: True
    view_all_submitted_projects: False

  student:
    modify_permissions: False
    create_project_groups: False
    modify_project_groups: False
    set_readonly: False
    create_projects: False
    review_other_projects: False
    join_projects: True
    view_projects_predeadline: False
    view_all_submitted_projects: False

deadlines:
  supervisor_submit:
    name: Submission deadline for supervisors
    pester: [create_projects]
    pester_content: submit your projects
  grad_office_review:
    name: Deadline for Grad Office review
    pester: [create_project_groups]
  student_invite:
    name: Date students get invited
    pester: []
  student_choice:
    name: Deadline for student choices
    pester: [join_projects]
  student_complete:
    name: Deadline for report submission
    pester: [join_projects]
  marking_complete:
    name: Deadline for feedback report
    pester: [join_projects]

misc:
  submission_grace_time: 3
  pester_time: [1, 7, 14]
  grades:
    - A - Excellent
    - B - Good
    - C - Satisfactory
    - D - Fail
  max_export_line_length: 30
  programmes:
    - Cancer, Ageing and Somatic Mutation
    - Cellular Genetics
    - Human Genetics
    - Infection Genomics
    - Malaria